# Homework 5: K-means Clustering

Due Tuesday March 5

The OptDigits data from the UCI ML repository will be classified using K-means clustering. Each data instance has 64 attributes (pixels) with a value between 0-16, along with the class label.

Clustering will be evaluated using average mean-square-error, mean- square-separation, mean entropy, and accuracy.

## Experiment 1
K = 10

1) Run 5 times with random initial seeds

    1b) Stop run when clusters stop changing
    
2) Choose run with smallest average MSE

In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt

In [4]:
# Load Data #64 attributes + 1 class = 65
traindata = pd.read_csv("optdigits.train", header = None)
testdata = pd.read_csv("optdigits.test", header = None)

print(traindata.head())
#testdata.head()
traindata = traindata.values #to numpy matrix
testdata = testdata.values

np.random.seed(0)

   0   1   2   3   4   5   6   7   8   9  ...  55  56  57  58  59  60  61  62  \
0   0   1   6  15  12   1   0   0   0   7 ...   0   0   0   6  14   7   1   0   
1   0   0  10  16   6   0   0   0   0   7 ...   0   0   0  10  16  15   3   0   
2   0   0   8  15  16  13   0   0   0   1 ...   0   0   0   9  14   0   0   0   
3   0   0   0   3  11  16   0   0   0   0 ...   0   0   0   0   1  15   2   0   
4   0   0   5  14   4   0   0   0   0   0 ...   0   0   0   4  12  14   7   0   

   63  64  
0   0   0  
1   0   0  
2   0   7  
3   0   4  
4   0   6  

[5 rows x 65 columns]


In [12]:
def rand_cent(data, k):
    """
    input:
        data: training data set, to compute length
        k: Number of centroids
    output:
        init_cents: array of random indicies into data, of size k
    """
    n = len(data) - 1
    init_cents = np.random.randint(0, n, k)
    return init_cents

def cluster(data, cents, k):
    """
    input:
        data: training data set, to compute euclidian distance (n x 64, STRIP CLASS a)
        k: Number of centroids
        cents: array (len: k) of centroids (k x 64 matrix)
    output:
        
    """
    dists = [] #k-size rows of euclidian distance between row = data_point, column = centroid
    for cent in cents:
        dist = np.linalg.norm(data - , axis = 1)

dists = [] #k-size rows of euclidian distance between row = data_point, column = centroid
closest = [] #Closest centroid 0:k
k = 10

print(rand_cent(traindata, k))


[3360 3337 2745  639  544 2591  714 2292  151 2723]


In [11]:
dist = np.linalg.norm(a-b)

NameError: name 'a' is not defined

In [25]:
a = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)
b = np.array([1,5,2])
print(b)
c = a-b
print(c)
#https://stackoverflow.com/questions/7741878/how-to-apply-numpy-linalg-norm-to-each-row-of-a-matrix
print(np.linalg.norm(c, axis = 1))
print(b.reshape(-1,1))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[1 5 2]
[[ 0 -3  1]
 [ 1 -2  2]
 [ 2 -1  3]]
[3.16227766 3.         3.74165739]
[[1]
 [5]
 [2]]
